# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'ApplozicSample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for ApplozicSample
    pod 'Applozic', '~>5.0.0'
 

  target 'ApplozicSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ApplozicSample-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ApplozicSample-tvOS

  target 'ApplozicSample-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
